### PR TITLE
Migration to Bevy 0.9

### PR DESCRIPTION
**Pull request by Jlabarca**
Migrated the lib and examples to bevy 0.9 and rapier 0.19

Also commented parts of the code throwing errors or unused
I guess you guys could check further if those might get removed or updated.

### CODE REVIEW

**Review by PROMETHIA-27 — COMMENTED** [review]
I'll take a look at this soon to fix up the errors. Thanks for the PR!

**Comment by Jlabarca** [comment]
Thanks! There are no errors though
An example might be incomplete, but it already was

**Comment by PROMETHIA-27** [comment]
I was referring to this
> Also commented parts of the code throwing errors or unused

**Review by Aceeri — APPROVED** [review]
This should be good now, bevy_editor_pls seems to be panicking on macos, so I removed it from the examples for now.

**Pull request merged**
